// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview This flow suggests recipes based on user-provided constraints, such as ingredients to avoid or use up.
 *
 * - suggestRecipesGivenConstraints - The main function to trigger the recipe suggestion flow.
 * - SuggestRecipesGivenConstraintsInput - The input type for the suggestRecipesGivenConstraints function.
 * - SuggestRecipesGivenConstraintsOutput - The output type for the suggestRecipesGivenConstraints function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestRecipesGivenConstraintsInputSchema = z.object({
  constraints: z
    .string()
    .describe(
      'Constraints for recipe suggestions, such as ingredients to avoid or use up.'
    ),
});

export type SuggestRecipesGivenConstraintsInput = z.infer<
  typeof SuggestRecipesGivenConstraintsInputSchema
>;

const SuggestRecipesGivenConstraintsOutputSchema = z.object({
  recipes: z
    .array(z.string())
    .describe('An array of suggested recipe names that meet the constraints.'),
});

export type SuggestRecipesGivenConstraintsOutput = z.infer<
  typeof SuggestRecipesGivenConstraintsOutputSchema
>;

export async function suggestRecipesGivenConstraints(
  input: SuggestRecipesGivenConstraintsInput
): Promise<SuggestRecipesGivenConstraintsOutput> {
  return suggestRecipesGivenConstraintsFlow(input);
}

const suggestRecipesGivenConstraintsPrompt = ai.definePrompt({
  name: 'suggestRecipesGivenConstraintsPrompt',
  input: {
    schema: SuggestRecipesGivenConstraintsInputSchema,
  },
  output: {
    schema: SuggestRecipesGivenConstraintsOutputSchema,
  },
  prompt: `Suggest recipes based on the following constraints: {{{constraints}}}.  Return an array of recipe names.`, 
});

const suggestRecipesGivenConstraintsFlow = ai.defineFlow(
  {
    name: 'suggestRecipesGivenConstraintsFlow',
    inputSchema: SuggestRecipesGivenConstraintsInputSchema,
    outputSchema: SuggestRecipesGivenConstraintsOutputSchema,
  },
  async input => {
    const {output} = await suggestRecipesGivenConstraintsPrompt(input);
    return output!;
  }
);
